//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_khác_sạn
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        public string manv { get; set; }
        public string macv { get; set; }
        public string tennv { get; set; }
        public Nullable<double> luong { get; set; }
        public string tinhtrang { get; set; }
    
        public virtual chucvu chucvu { get; set; }
    }
}
